const dogsData = [
	{
		id: "1",
		breed: "Beagle",
		image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZp3ggA0Bp1H2l2VQPWs0m9sZ6kfn2h87DRg&s",
		size: "small to medium",
		exercise: "2 hours a day",
		temperament: "Intelligent, friendly, excitable",
		options: ["Boston Terrier", "Pug", "Collie", "Beagle"],
		answer: "Beagle",
		favorites: false,
	},
	{
		id: "2",
		breed: "Brittany Spaniel",
		image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU2hATbC9ewdkgKzxs34lClrS8wI2EVZKgqQ&s",
		size: "medium",
		exercise: "6 hours a day",
		temperament: "Attentive, happy, quick, intelligent, agile, adaptable",
		options: ["Brittany Spaniel", "Basset Hound", "Jack Russell Terrier", "Beagle"],
		answer: "Brittany Spaniel",
		favorites: false,
	},
	{
		id: "3",
		breed: "Doberman Pinscher",
		image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Q5i3a-0UNhpM4XtSHHXcN1MlOnomKEOjEA&s",
		size: "large",
		exercise: "2 hours a day",
		temperament: "Intelligent, loyal, and alert",
		options: ["American Pitbull", "Doberman Pinscher", "Greyhound", "Mastiff"],
		answer: "Doberman Pinscher",
		favorites: false,
	},
	{
		id: "4",
		breed: "Norwegian Elkhound",
		image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDk7EXLnJ9j-_aOLe9hmypSESO65P1ZMh1XQ&s",
		size: "medium",
		exercise: "4 hours a day",
		temperament: "Loyal, friendly, affectionate",
		options: ["Norwegian Elkhound", "German Shepherd", "Tibetan Mastiff", "Siberian Husky"],
		answer: "Norwegian Elkhound",
		favorites: false,
	},
	{
		id: "5",
		breed: "Basenji",
		image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoEiKpVTXDz2K1qTwIvbQOmiPV1AwuhFV9rw&s",
		size: "small to medium",
		exercise: "3 hours a day",
		temperament: "Intelligent, independent, quiet, and alert",
		options: ["Smooth Fox Terrier", "Shih Tzu", "Basenji", "Chihuahua"],
		answer: "Basenji",
		favorites: false,
	},
]

export default dogsData;